### ISSUE TITLE
"Show this show now" does not immediately render the given show and makes the screen blank

### ISSUE THREAD

**Issue by ChiWilliams** [gregsadetsky/rapidriteros#10]
Sorry for the cursed issue title. Clicking "show this show now" does not immediately switch to the selected show on the actual RapidRiter. It leads to a blank page (like [this](https://rapidriter.rcdis.co/set_immediately_show_show/99) for instance), and nothing happens.

Given that it worked locally, I wonder if this is an issue with how the things talks with the server? When I called get_immediately_show_show using the [webpage](https://rapidriter.rcdis.co/get_immediately_show_show), the response was null instead of the show I had set as expected. @bcspragu

**Comment by gregsadetsky** [comment]
Yeah, the page is not fully blank, there's a little "ok" on there :) but yeah that POST submission could just redirect back to the index page

As for why it's not happening immediately - I think there are maybe too many things going on (ie checks for immediately osc, immediately showing a show, fetching whether the "immediate" flags have been set etc) that are just beyond hellish to debug - this is entirely my fault.

The more right approach would be for the worker to ... actually also be a web service, and accept pushed (server side events) from the main web process. That way no need to do http requests between each frame (!!), no need for the KV stuff, etc

Would be happy to pair on this after the 19th (my talk re disco)!!

**Comment by bcspragu** [comment]
I've noticed this locally, but what I see is not that "nothing happens", but rather it might not happen immediately. I notice this specifically with the text renderer. Since we can only 'hook' when a new frame is rendered, we're at the whims of renderers to send down a fresh frame, which they may not do urgently

**Comment by gregsadetsky** [comment]
Right, good point. The renderers deciding when to send down a frame (i.e. both sending image data but also introducing sleeps) most definitely contributes to any delay here
