### ISSUE TITLE
wasm

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/rapidriteros#11]
heya! @bcspragu 

so good news is that the wasm renderer seems to work - both locally and on the riter

in that... it runs? and there are no errors.

but... nothing shows up with the [test program](https://github.com/gregsadetsky/rapidriteros/pull/7#issuecomment-2480427952) :-)

when you ran the test program locally (i.e. running all of the rapidriter debugging locally), did you see the debug output (in the worker terminal) show pixels on/off?

I see the below which indicates all LEDs off:

<img width="802" alt="image" src="https://github.com/user-attachments/assets/5cf3b297-db7a-4365-a265-e4820ae9bc51">

---

let me know! thanks so much for your work!!!

**Comment by gregsadetsky** [comment]
heya, just to continue the conversion we had in #12 ...

we have wasm first light :-)

https://www.youtube.com/shorts/DRcf375FNSA

it seems to pause in between line "bursts" and also it doesn't fill the whole screen but.......... it's getting really really really close?

is that what you expected to see re: the wasm program? I used [the latest one](https://github.com/gregsadetsky/rapidriteros/pull/12#issuecomment-2492703073) you provided

lmk!! congrats!!!!!!1 wasm!!!!!!!!!!!!!!11

**Comment by gregsadetsky** [comment]
I'm running the wasm renderer locally and I do see the same - bursts of pixel lines, and it doesn't go from the top left pixel to the bottom right, right?

just making sure! but yeah, on the real riter, it does look like what's in the terminal...!! so that's a good sign!!!

**Comment by bcspragu** [comment]
WASM!!!111!! indeed!

> it doesn't fill the whole screen

This is expected! Not sure why I did this, but the [simpletest program](https://git.sr.ht/~bsprague/recurse/tree/main/item/rapidriter/simpletest/src/lib.rs) goes for 100 frames ([the limit](https://github.com/gregsadetsky/rapidriteros/blob/11d1f7e261e847b4d3913d0bb532dcddeffd8cdc/renderers/wasm/src/main.rs#L59) in the WASM renderer), moving 20 pixels each time. (20 px * 100 frames) / (96px width * 38 px height)  = ~55% of the total screen real estate, which looks about right

> it seems to pause in between line "bursts"

This was unexpected (but as you noted, also visible in the terminal logging which I should *really* stop writing off), but looking back at the code I see a [VERY SUSPICIOUS ONE SECOND DELAY](https://github.com/gregsadetsky/rapidriteros/blob/11d1f7e261e847b4d3913d0bb532dcddeffd8cdc/renderers/wasm/src/main.rs#L131) that I forgot to remove from the example code I started from :facepalm: 

I'll send a follow-up PR that tweaks a few things and should leave us with some buttery smooth wasm goodness.

Thanks again for all your help and physical hub presence!

**Comment by gregsadetsky** [comment]
incredible!!!!!!!!!!! congrats!! feel free to ping me here / zulip. I'm here for a bit! sorry I didn't bring the webcam but I do think it'd be a neat idea!

**Comment by bcspragu** [comment]
Hmm actually something else is afoot! It looks like the WASM renderer is sending frames out at a pretty consistent pace, and things are getting gunked up somewhere else: https://asciinema.org/a/a9Q7MnRtPxoTweDDnxFHxpgdE

**Comment by gregsadetsky** [comment]
interesting! when I debug this by adding a print right underneath the `if event.event == "screen_update"`, I get this:

notice the events around `16:48:56.100` and then the pause and then `16:48:56.919246`

<details>

<summary>print output with timestamp</summary>

```
screen_update event! 2024-11-24 16:48:56.097560
screen_update event! 2024-11-24 16:48:56.098258
screen_update event! 2024-11-24 16:48:56.098495
screen_update event! 2024-11-24 16:48:56.098733
screen_update event! 2024-11-24 16:48:56.098894
screen_update event! 2024-11-24 16:48:56.099187
screen_update event! 2024-11-24 16:48:56.099461
screen_update event! 2024-11-24 16:48:56.099619
screen_update event! 2024-11-24 16:48:56.099780
screen_update event! 2024-11-24 16:48:56.099973
screen_update event! 2024-11-24 16:48:56.100114
screen_update event! 2024-11-24 16:48:56.100259
screen_update event! 2024-11-24 16:48:56.100439
screen_update event! 2024-11-24 16:48:56.100588
screen_update event! 2024-11-24 16:48:56.100731
screen_update event! 2024-11-24 16:48:56.100864
screen_update event! 2024-11-24 16:48:56.919246
screen_update event! 2024-11-24 16:48:56.919730
screen_update event! 2024-11-24 16:48:56.919896
screen_update event! 2024-11-24 16:48:56.920116
screen_update event! 2024-11-24 16:48:56.920252
screen_update event! 2024-11-24 16:48:56.920422
screen_update event! 2024-11-24 16:48:56.920594
screen_update event! 2024-11-24 16:48:56.920766
screen_update event! 2024-11-24 16:48:56.920992
screen_update event! 2024-11-24 16:48:56.921203
screen_update event! 2024-11-24 16:48:56.921380
screen_update event! 2024-11-24 16:48:56.921534
screen_update event! 2024-11-24 16:48:56.921709
screen_update event! 2024-11-24 16:48:56.921872
screen_update event! 2024-11-24 16:48:56.922044
screen_update event! 2024-11-24 16:48:56.922256
screen_update event! 2024-11-24 16:48:57.734150
screen_update event! 2024-11-24 16:48:57.734788
screen_update event! 2024-11-24 16:48:57.735110
screen_update event! 2024-11-24 16:48:57.735271
screen_update event! 2024-11-24 16:48:57.735625
screen_update event! 2024-11-24 16:48:57.735869
screen_update event! 2024-11-24 16:48:57.736102
screen_update event! 2024-11-24 16:48:57.736334
screen_update event! 2024-11-24 16:48:57.736465
screen_update event! 2024-11-24 16:48:57.736607
screen_update event! 2024-11-24 16:48:57.736747
screen_update event! 2024-11-24 16:48:57.736901
screen_update event! 2024-11-24 16:48:57.737141
screen_update event! 2024-11-24 16:48:57.737284
screen_update event! 2024-11-24 16:48:57.737482
screen_update event! 2024-11-24 16:48:57.737604
screen_update event! 2024-11-24 16:48:58.560266
screen_update event! 2024-11-24 16:48:58.560911
screen_update event! 2024-11-24 16:48:58.561344
screen_update event! 2024-11-24 16:48:58.561689
screen_update event! 2024-11-24 16:48:58.561988
screen_update event! 2024-11-24 16:48:58.562174
screen_update event! 2024-11-24 16:48:58.562354
screen_update event! 2024-11-24 16:48:58.562722
screen_update event! 2024-11-24 16:48:58.562915
screen_update event! 2024-11-24 16:48:58.563250
screen_update event! 2024-11-24 16:48:58.563423
screen_update event! 2024-11-24 16:48:58.563623
screen_update event! 2024-11-24 16:48:58.563818
screen_update event! 2024-11-24 16:48:58.564208
screen_update event! 2024-11-24 16:48:58.564391
screen_update event! 2024-11-24 16:48:58.564450
screen_update event! 2024-11-24 16:48:59.376725
screen_update event! 2024-11-24 16:48:59.377089
screen_update event! 2024-11-24 16:48:59.377281
screen_update event! 2024-11-24 16:48:59.377464
screen_update event! 2024-11-24 16:48:59.377663
screen_update event! 2024-11-24 16:48:59.377832
screen_update event! 2024-11-24 16:48:59.377998
screen_update event! 2024-11-24 16:48:59.378151
screen_update event! 2024-11-24 16:48:59.378290
screen_update event! 2024-11-24 16:48:59.378449
screen_update event! 2024-11-24 16:48:59.378599
screen_update event! 2024-11-24 16:48:59.378743
screen_update event! 2024-11-24 16:48:59.378916
screen_update event! 2024-11-24 16:48:59.379051
screen_update event! 2024-11-24 16:48:59.379188
screen_update event! 2024-11-24 16:48:59.379325
screen_update event! 2024-11-24 16:49:00.200590
screen_update event! 2024-11-24 16:49:00.201126
screen_update event! 2024-11-24 16:49:00.201904
screen_update event! 2024-11-24 16:49:00.202181
screen_update event! 2024-11-24 16:49:00.202481
screen_update event! 2024-11-24 16:49:00.202743
screen_update event! 2024-11-24 16:49:00.202959
screen_update event! 2024-11-24 16:49:00.203127
screen_update event! 2024-11-24 16:49:00.203312
screen_update event! 2024-11-24 16:49:00.203511
screen_update event! 2024-11-24 16:49:00.203681
screen_update event! 2024-11-24 16:49:00.203858
screen_update event! 2024-11-24 16:49:00.204076
screen_update event! 2024-11-24 16:49:00.204337
screen_update event! 2024-11-24 16:49:00.204542
screen_update event! 2024-11-24 16:49:00.204701
screen_update event! 2024-11-24 16:49:00.403278
screen_update event! 2024-11-24 16:49:00.403824
screen_update event! 2024-11-24 16:49:00.404170
screen_update event! 2024-11-24 16:49:00.404398
screen_update event! 2024-11-24 16:49:00.404696
```

</details>

**Comment by gregsadetsky** [comment]
also in your asciicinema, you were showing a text show, not the wasm show -- have you tried running a wasm show locally and seeing if the burst rate is as stable..?

**Comment by bcspragu** [comment]
> also in your asciicinema, you were showing a text show, not the wasm show 

Confusingly, I was showing the wasm show, I had just shut off the logging for WASM shows because it was super noisy (it prints the whole WASM program text)

**Comment by bcspragu** [comment]
Also, my dog is demanding a hike, so I'll be back to debug this later!

![gtr62](https://github.com/user-attachments/assets/e118c57b-bc0f-421f-b209-3fea38f33d1e)

**Comment by gregsadetsky** [comment]
ah yeah I fixed/changed this so that it just prints the show type and the first 100 chars - I agree that it's noisy, but I prefer to see some debugging

hmm ok... it's weird that my local terminal and the riter output agree on the burst/pauses

hahaha cutie patootie haha no worries!

I can only really point to [this line](https://github.com/gregsadetsky/rapidriteros/blob/main/renderers/wasm/src/main.rs#L104) as potentially... the issue? like... what would happen if you didn't sleep there? I mean it'd burst the frames too fast but... would it get rid of these hiccups?

**Comment by gregsadetsky** [comment]
ok just pushed a bunch of changes. the most important one that I'm really happy about is that I moved from the worker pinging the django web process between every frame to see if there is an "immediate show" and moved all of that to server side events (i.e. everybody is just "smartly" async awaiting for an event instead of polling)

anyway, that's live and it works. (I also temporarily disabled OSC, I'll come back to it)

but... I'm still seeing the same "bursts" in the wasm.

want to git pull and run all of this locally and see how it looks?

thanks again for your help!!

**Comment by bcspragu** [comment]
> I can only really point to [this line](https://github.com/gregsadetsky/rapidriteros/blob/main/renderers/wasm/src/main.rs#L104) as potentially... the issue? like... what would happen if you didn't sleep there? I mean it'd burst the frames too fast but... would it get rid of these hiccups?

Great minds think alike :) I had actually removed those lines prior to either of those asciinemas. I'll pull your changes and poke around more

**Comment by bcspragu** [comment]
Hmm, so after poking around everything just...seems to work?? https://asciinema.org/a/DMO3nlcxUe8NrsDGeIa0789kr

It was probably my buggy `sleep` code, but even after removing that the terminal output was kinda garbled and looked bad, but switching it from `print` to `log.info` makes it more legible. I think something about how `log` is set up makes it swallow `print` statements.

In any case, I'll send out the WASM updates, I think we're in the clear! :crossed_fingers:

**Comment by gregsadetsky** [comment]
oh amazing!! yeah send the code when you can, I'll test it locally and deploy and take a look!
